--- This file was automatically generated by utils/generate_semantic_conventions.lua
-- See: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions
--
-- module @semantic_conventions.trace.compatibility
local _M = {
    -- Parent-child Reference type
    OPENTRACING_REF_TYPE = "opentracing.ref_type"
}
return _M
