--- This file was automatically generated by utils/generate_semantic_conventions.lua
-- See: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions
--
-- module @semantic_conventions.trace.database
local _M = {
    -- An identifier for the database management system (DBMS) product being used. See below for a list of well-known identifiers.
    db_system = "db.system",
    -- The connection string used to connect to the database. It is recommended to remove embedded credentials.
    db_connection_string = "db.connection_string",
    -- Username for accessing the database.
    db_user = "db.user",
    -- The fully-qualified class name of the [Java Database Connectivity (JDBC)](https://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/) driver used to connect.
    db_jdbc_driver_classname = "db.jdbc.driver_classname",
    -- This attribute is used to report the name of the database being accessed. For commands that switch the database, this should be set to the target database (even if the command fails).
    db_name = "db.name",
    -- The database statement being executed.
    db_statement = "db.statement",
    -- The name of the operation being executed, e.g. the [MongoDB command name](https://docs.mongodb.com/manual/reference/command/#database-operations) such as `findAndModify`, or the SQL keyword.
    db_operation = "db.operation",
    -- The Microsoft SQL Server [instance name](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15) connecting to. This name is used to determine the port of a named instance.
    db_mssql_instance_name = "db.mssql.instance_name",
    -- The fetch size used for paging, i.e. how many rows will be returned at once.
    db_cassandra_page_size = "db.cassandra.page_size",
    -- The consistency level of the query. Based on consistency values from [CQL](https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlConfigConsistency.html).
    db_cassandra_consistency_level = "db.cassandra.consistency_level",
    -- The name of the primary table that the operation is acting upon, including the keyspace name (if applicable).
    db_cassandra_table = "db.cassandra.table",
    -- Whether or not the query is idempotent.
    db_cassandra_idempotence = "db.cassandra.idempotence",
    -- The number of times a query was speculatively executed. Not set or `0` if the query was not executed speculatively.
    db_cassandra_speculative_execution_count = "db.cassandra.speculative_execution_count",
    -- The ID of the coordinating node for a query.
    db_cassandra_coordinator_id = "db.cassandra.coordinator.id",
    -- The data center of the coordinating node for a query.
    db_cassandra_coordinator_dc = "db.cassandra.coordinator.dc",
    -- The index of the database being accessed as used in the [`SELECT` command](https://redis.io/commands/select), provided as an integer. To be used instead of the generic `db.name` attribute.
    db_redis_database_index = "db.redis.database_index",
    -- The collection being accessed within the database stated in `db.name`.
    db_mongodb_collection = "db.mongodb.collection",
    -- The name of the primary table that the operation is acting upon, including the database name (if applicable).
    db_sql_table = "db.sql.table"
}
return _M
