--- This file was automatically generated by utils/generate_semantic_conventions.lua
-- See: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions
--
-- module @semantic_conventions.trace.exporter
local _M = {
    -- Name of the code, either "OK" or "ERROR". MUST NOT be set if the status code is UNSET.
    OTEL_STATUS_CODE = "otel.status_code",
    -- Description of the Status if it has a value, otherwise not set.
    OTEL_STATUS_DESCRIPTION = "otel.status_description"
}
return _M
