--- This file was automatically generated by utils/generate_semantic_conventions.lua
-- See: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions
--
-- module @semantic_conventions.trace.trace
local _M = {
    -- SHOULD be set to true if the exception event is recorded at a point where it is known that the exception is escaping the scope of the span.
    EXCEPTION_ESCAPED = "exception.escaped"
}
return _M
