name: test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
      - "update-ci"
  pull_request:
    branches:
      - main

jobs:
  build-openresty:
    name: "Build openresty image"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          outputs: type=docker,dest=/tmp/openresty-image.tar
          tags: opentelemetry-lua_openresty
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: openresty-image
          path: /tmp/openresty-image.tar
  end-to-end-tests:
    name: "End to end tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - build-openresty
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v4
        with:
          context: examples/server
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: opentelemetry-lua_test-server
      - uses: docker/build-push-action@v4
        with:
          context: examples/client
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: opentelemetry-lua_test-client
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: openresty-image
          path: /tmp
      - name: Load Docker images
        run: |
          docker load --input /tmp/openresty-image.tar
          docker image ls -a
      - name: Start containers
        run: make openresty-dev CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"
      - name: Run openresty integration tests
        run: make openresty-integration-test CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"
      - name: Run openresty-test-e2e-trace-context
        run: make openresty-test-e2e-trace-context CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"
      - name: Run openresty-test-e2e
        run: make openresty-test-e2e CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"

  unit-tests:
    name: "unit tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - build-openresty
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: openresty-image
          path: /tmp
      - name: Load Docker images
        run: |
          docker load --input /tmp/openresty-image.tar
          docker image ls -a
      - name: Run busted unit tests
        run: make lua-unit-test
      - name: Run api tests
        run: make api-test
  book-keeping:
    name: "Book-keeping"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v4
        with:
          context: utils
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: opentelemetry-lua_utils
      - run: make check-format
